spring.application.name=Women-safety-project

spring.data.mongodb.uri=mongodb+srv://WomenSecurity:t3K5ZFtzEur3tJvP@project.6uunglo.mongodb.net/WomenSafety?retryWrites=true&w=majority


spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG